from typing import Callable  # noqa: EXE002

class YTicker:
    def start_websocket(
        self,
        message_update_callback: Callable[[], None],
        error_callback: Callable[[], None] | None = None,
        open_callback: Callable[[], None] | None = None,
        close_callback: Callable[[], None] | None = None,
    ) -> None: ...
    def close_websocket(self) -> None: ...
    async def subscribe(self, instruments: list[str]) -> None: ...
    async def unsubscribe(self, instruments: list[str]) -> None: ...
